# Generated by Django 6.0.6 on 2026-07-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_activity', models.CharField(choices=[('raw', 'سكني'), ('commercial', 'تجاري')], default='raw', max_length=50, verbose_name='نشاط البناء')),
                ('Request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_info', to='Client.visitdetails', verbose_name='الزيارة المرتبطة')),
            ],
        ),
    ]
