# Generated by Django 6.0.6 on 2026-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='building_activity',
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مسطحات البناء (م²)'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_east',
            field=models.BooleanField(default=False, verbose_name='شرقية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم رخصة البناء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_north',
            field=models.BooleanField(default=False, verbose_name='شمالية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_south',
            field=models.BooleanField(default=False, verbose_name='جنوبية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='building_west',
            field=models.BooleanField(default=False, verbose_name='غربية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='design_office',
            field=models.CharField(blank=True, max_length=200, verbose_name='المكتب المصمم'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='detailed_address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_architectural_plans',
            field=models.BooleanField(default=False, verbose_name='المخططات المعمارية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_building_license',
            field=models.BooleanField(default=False, verbose_name='رخصة البناء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_electrical_plans',
            field=models.BooleanField(default=False, verbose_name='المخططات الكهربائية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_eng_supervision',
            field=models.BooleanField(default=False, verbose_name='شهادة إشراف مكتب هندسي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_finishes_warranty',
            field=models.BooleanField(default=False, verbose_name='شهادة ضمان التشطيبات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_mechanical_plans',
            field=models.BooleanField(default=False, verbose_name='المخططات الميكانيكية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_rebar_report',
            field=models.BooleanField(default=False, verbose_name='تقرير استلام حديد التسليح'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_soil_test',
            field=models.BooleanField(default=False, verbose_name='تقرير فحص التربة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_structural_plans',
            field=models.BooleanField(default=False, verbose_name='المخططات الإنشائية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_structural_warranty',
            field=models.BooleanField(default=False, verbose_name='ضمان الهيكل الإنشائي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='doc_survey_form',
            field=models.BooleanField(default=False, verbose_name='استمارة الرفع المساحي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='electricity_meter_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم عداد كهرباء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='electricity_meter_reading',
            field=models.CharField(blank=True, max_length=100, verbose_name='قراءة عداد الكهرباء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='engineering_supervisor',
            field=models.CharField(blank=True, max_length=200, verbose_name='المشرف الهندسي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_cameras',
            field=models.BooleanField(default=False, verbose_name='كاميرات مراقبة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_central_ac',
            field=models.BooleanField(default=False, verbose_name='تكييف مركزي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_disabled_friendly',
            field=models.BooleanField(default=False, verbose_name='صديق للمعاقين وكبار السن'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_elevator',
            field=models.BooleanField(default=False, verbose_name='مصعد كهربائي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_fire_system',
            field=models.BooleanField(default=False, verbose_name='نظام مكافحة الحرائق'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_garden',
            field=models.BooleanField(default=False, verbose_name='حديقة داخلية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_outdoor_seating',
            field=models.BooleanField(default=False, verbose_name='جلسة خارجية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_parking',
            field=models.BooleanField(default=False, verbose_name='موقف السيارة (جراج)'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح (حمام سباحة)'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_skylight',
            field=models.BooleanField(default=False, verbose_name='فتحة إنارة سقفية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='feat_water_tanks',
            field=models.BooleanField(default=False, verbose_name='خزانات ماء أرضية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_asphalt',
            field=models.BooleanField(default=False, verbose_name='طرق أسفلت'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_electricity',
            field=models.BooleanField(default=False, verbose_name='مرفق كهرباء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_lighting',
            field=models.BooleanField(default=False, verbose_name='طرق منارة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_network',
            field=models.BooleanField(default=False, verbose_name='شبكة إتصال'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_sewage',
            field=models.BooleanField(default=False, verbose_name='صرف صحي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='infra_water',
            field=models.BooleanField(default=False, verbose_name='مرفق مياة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='inspection_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الفحص'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الطوابق'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='property_age_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عمر العقار بالسنوات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='property_condition',
            field=models.CharField(choices=[('furnished', 'مشطب - مؤثث'), ('unfurnished', 'مشطب - غير مؤثث'), ('raw', 'عظم')], default='unfurnished', max_length=50, verbose_name='حالة العقار'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='property_developer',
            field=models.CharField(blank=True, max_length=200, verbose_name='المطور العقاري'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='property_owner',
            field=models.CharField(blank=True, max_length=200, verbose_name='مالك العقار'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='street_east',
            field=models.BooleanField(default=False, verbose_name='شرقي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='street_north',
            field=models.BooleanField(default=False, verbose_name='شمالي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='street_south',
            field=models.BooleanField(default=False, verbose_name='جنوبي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='street_west',
            field=models.BooleanField(default=False, verbose_name='غربي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الوحدة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='water_meter_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم عداد الماء'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='water_meter_reading',
            field=models.CharField(blank=True, max_length=100, verbose_name='قراءة عداد الماء'),
        ),
    ]
