# Generated by Django 6.0.6 on 2026-07-12 10:51

import Visits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0002_remove_visitreport_building_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to=Visits.models.DynamicPathUploader('property_image'), verbose_name='صورة العقار'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='detailed_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='property_owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مالك العقار'),
        ),
    ]
