# Generated by Django 6.0.6 on 2026-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0003_visitreport_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='inspection_time',
        ),
        migrations.AddField(
            model_name='visitreport',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='الوقت'),
        ),
    ]
