# Generated by Django 6.0.6 on 2026-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0004_remove_visitreport_inspection_time_visitreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('furnished', 'مشطب - مؤثث'), ('unfurnished', 'مشطب - غير مؤثث'), ('raw', 'عظم')], default='unfurnished', max_length=50, null=True, verbose_name='حالة العقار'),
        ),
    ]
