# Generated by Django 6.0.6 on 2026-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0005_alter_visitreport_property_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='property_condition',
            field=models.CharField(choices=[('furnished', 'مشطب - مؤثث'), ('unfurnished', 'مشطب - غير مؤثث'), ('raw', 'عظم')], default='unfurnished', max_length=50, verbose_name='حالة العقار'),
        ),
    ]
