# Generated by Django 6.0.6 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0006_alter_visitreport_property_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='building_activity',
            field=models.CharField(choices=[('furnished', 'مشطب - مؤثث'), ('unfurnished', 'مشطب - غير مؤثث'), ('raw', 'عظم')], default='unfurnished', max_length=50, verbose_name='نشاط البناء'),
        ),
    ]
