# Generated by Django 6.0.6 on 2026-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0007_visitreport_building_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='general_comment',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق عام'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='building_activity',
            field=models.CharField(choices=[('raw', 'سكني'), ('commercial', 'تجاري')], default='raw', max_length=50, verbose_name='نشاط البناء'),
        ),
    ]
