# Generated by Django 6.0.6 on 2026-07-13 21:19

import Visits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0008_visitreport_general_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Visits.models.general_report_image_upload_path, verbose_name='الصورة العامة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_images', to='Visits.visitreport', verbose_name='تقرير الزيارة المرتبط')),
            ],
        ),
    ]
