# Generated by Django 6.0.6 on 2026-07-14 15:36

import Visits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0009_visitreportimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='general_comment',
        ),
        migrations.CreateModel(
            name='InspectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('general', 'تقرير عام'), ('lounge', 'الصالة'), ('kitchen', 'المطبخ'), ('bathroom', 'الحمام'), ('bedroom', 'غرفة النوم'), ('entrance', 'المدخل')], default='general', max_length=20, verbose_name='نطاق الفحص')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='تعليق عام')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Visits.visitreport')),
            ],
        ),
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name=Visits.models.general_report_image_upload_path)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Visits.inspectionarea')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Visits.inspectionarea')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitReportImage',
        ),
    ]
