# Generated by Django 6.0.6 on 2026-07-15 17:55

import Visits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0010_remove_visitreport_general_comment_inspectionarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaimage',
            name='image',
            field=models.ImageField(upload_to=Visits.models.general_report_image_upload_path),
        ),
    ]
