# Generated by Django 6.0.6 on 2026-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0011_alter_areaimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='key',
            field=models.CharField(choices=[('electrical', 'الكهرباء'), ('plumbing', 'السباكة'), ('cracks', 'التشققات'), ('moisture', 'الرطوبة'), ('walls', 'الجدران والدهانات'), ('ceilings', 'الأسقف'), ('floors', 'الأرضيات'), ('hvac', 'التكييف'), ('doors', 'الأبواب'), ('windows', 'النوافذ'), ('waterproofing', 'العزل المائي'), ('insulation', 'العزل الحراري'), ('other', 'أخرى')], default='electrical', max_length=20, unique=True, verbose_name='البند'),
            preserve_default=False,
        ),
    ]
