# Generated by Django 6.0.6 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0012_inspectionitem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='key',
            field=models.CharField(choices=[('electrical', 'الكهرباء'), ('plumbing', 'السباكة'), ('cracks', 'التشققات'), ('moisture', 'الرطوبة'), ('walls', 'الجدران والدهانات'), ('ceilings', 'الأسقف'), ('floors', 'الأرضيات'), ('hvac', 'التكييف'), ('doors', 'الأبواب'), ('windows', 'النوافذ'), ('waterproofing', 'العزل المائي'), ('insulation', 'العزل الحراري'), ('other', 'أخرى')], max_length=20, verbose_name='البند'),
        ),
    ]
