# Generated by Django 6.0.6 on 2026-07-21 17:29

import Visits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0013_alter_inspectionitem_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='أدخل قيمة بين 0 و 100', verbose_name='نسبة التقييم (%)'),
        ),
        migrations.CreateModel(
            name='InspectionItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Visits.models.inspection_item_image_upload_path)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Visits.inspectionitem')),
            ],
        ),
    ]
