# Generated by Django 6.0.6 on 2026-07-21 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0014_inspectionitem_score_inspectionitemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='أدخل قيمة بين 0 و 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التقييم (%)'),
        ),
    ]
