# Generated by Django 6.0.6 on 2026-07-21 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0015_alter_inspectionitem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
