# Generated by Django 6.0.6 on 2026-07-23 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0016_inspectionitem_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
