# Generated by Django 6.0.6 on 2026-08-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0017_alter_inspectionitem_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='نص التوصية')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='Visits.visitreport')),
            ],
        ),
    ]
