# Generated by Django 6.0.6 on 2026-08-01 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0018_reportrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecommendation',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reportrecommendation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='نص التوصية'),
        ),
        migrations.AddConstraint(
            model_name='reportrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('text__isnull', False), models.Q(('text', ''), _negated=True)), fields=('visit', 'text'), name='unique_non_empty_text_per_visit'),
        ),
    ]
