# Generated by Django 6.0.6 on 2026-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0019_alter_reportrecommendation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionarea',
            name='key',
            field=models.CharField(choices=[('general', 'تقرير عام'), ('bedroom', 'غرفة نوم'), ('lounge', 'صالة'), ('majlis', 'مجلس'), ('bathroom', 'دورة مياه'), ('kitchen', 'مطبخ'), ('corridor', 'ممر'), ('entrance', 'مدخل'), ('warehouse', 'مستودع'), ('laundry_room', 'غرفة الغسيل'), ('balcony', 'بلكونة'), ('roof', 'سطح'), ('outdoor_areas', 'المناطق الخارجية'), ('underground_water_tank', 'الخزان الارضي')], default='general', max_length=25, verbose_name='نطاق الفحص'),
        ),
    ]
