# Generated by Django 6.0.6 on 2026-07-05 14:03

import Admin.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='المفتاح')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='الاسم')),
                ('user', models.CharField(blank=True, max_length=50, verbose_name='اليوزر')),
                ('link', models.CharField(max_length=255, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة (اختياري)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=Admin.models.generate_coupon, max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='سيرفر SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='المنفذ')),
                ('use_tls', models.BooleanField(default=True, verbose_name='استخدام TLS (أمان حديث)')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='استخدام SSL (أمان قديم)')),
                ('email_user', models.EmailField(max_length=254, verbose_name='إيميل الإرسال')),
                ('email_password', models.CharField(max_length=100, verbose_name='كلمة مرور التطبيق')),
                ('email_subject', models.CharField(default='كود التحقق الخاص بك', max_length=200, verbose_name='عنوان الرسالة')),
                ('email_body', models.TextField(verbose_name='نص الرسالة (قبل الكود)')),
                ('company_name', models.CharField(default='نظام فولت', max_length=100, verbose_name='اسم الشركة للتذيل')),
                ('send_to_console', models.BooleanField(default=True, verbose_name='إرسال للكونسول فقط؟ (للتجربة)')),
            ],
            options={
                'verbose_name': 'إعدادات نظام الإيميل الثابتة',
                'verbose_name_plural': 'إعدادات نظام الإيميل الثابتة',
            },
        ),
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='نسبة الضريبة (%)')),
                ('company_profit_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='نسبة أرباح المنشأة من الضريبة (%)')),
                ('engineer_profit_percent', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='نسبة أرباح المهندس من الضريبة (%)')),
            ],
            options={
                'verbose_name': 'إعدادات مالية',
                'verbose_name_plural': 'إعدادات مالية',
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='المفتاح (EN)')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم (AR)')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='المفتاح (كود البوابة)')),
                ('name', models.CharField(max_length=50, verbose_name='اسم وسيلة الدفع')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعلة / معطلة')),
            ],
            options={
                'verbose_name': 'وسيلة دفع',
                'verbose_name_plural': 'وسائل الدفع',
            },
        ),
        migrations.CreateModel(
            name='PropertyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='المفتاح التقني')),
                ('property_name', models.CharField(max_length=100, verbose_name='اسم العقار')),
                ('std_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر العادي')),
                ('comp_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشامل')),
                ('meter_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر المتر الإضافي')),
                ('free_meters', models.IntegerField(default=200, verbose_name='عدادات مجانية')),
                ('is_active', models.BooleanField(default=True, verbose_name='الحالة')),
                ('allowed_duration', models.DurationField(default=datetime.timedelta(days=2), verbose_name='المدة المسموحة')),
            ],
            options={
                'verbose_name': 'تسعيرة العقارات',
                'verbose_name_plural': 'تسعيرات العقارات',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Region Key/Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region Name')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('radius', models.PositiveIntegerField(default=30000, verbose_name='Coverage Radius')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='المفتاح')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('enabled', models.BooleanField(default=True, verbose_name='تفعيل النشر التلقائي')),
                ('delay', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة النشر بالدقائق')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=20, unique=True, verbose_name='الاسم بالانجليزية')),
                ('name_ar', models.CharField(max_length=20, unique=True, verbose_name='الاسم بالعربية')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر الإجمالي لليوم')),
                ('is_working', models.BooleanField(default=True, help_text='قم بإلغاء التحديد لتعطيل هذا اليوم', verbose_name='يوم عمل؟')),
            ],
            options={
                'verbose_name': 'وقت العمل اليومي',
                'verbose_name_plural': 'أوقات العمل اليومية',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='اكتب اسم الفترة هنا (مثلاً: الصباح، العصر، إلخ)', max_length=50, verbose_name='اسم الفترة')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('is_booked', models.BooleanField(default=False, verbose_name='هل هي محجوزة؟')),
                ('day', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Admin.workingday')),
            ],
        ),
    ]
