# Generated by Django 6.0.6 on 2026-07-05 14:03

import Client.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=Client.models.generate_order_number, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('order_type', models.CharField(choices=[('visit', 'زيارة'), ('consultation', 'استشارة')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='هل تم التحقق؟')),
                ('applied_for_job', models.BooleanField(default=False, verbose_name='حالة التقديم على وظيفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationDetails',
            fields=[
                ('consultation_id', models.CharField(default=Client.models.generate_order_number, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح', regex='^\\+?\\d{9,15}$')], verbose_name='رقم الجوال')),
                ('summary', models.TextField(verbose_name='وصف الاستشارة')),
                ('work_day', models.CharField(blank=True, max_length=20, null=True)),
                ('work_time', models.CharField(max_length=50)),
                ('work_history', models.DateField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'قيد الانتظار'), ('published', 'تم النشر'), ('in_progress', 'جاري الفحص'), ('completed', 'تم الانتهاء')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Client.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ بعد الضريبة')),
                ('engineer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المهندس')),
                ('platform_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المنصة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('success', 'تم الدفع بنجاح'), ('failed', 'فشل الدفع'), ('cancel', 'تم إلغاؤه')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Client.order', verbose_name='الطلب')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.userphone'),
        ),
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('visit_id', models.CharField(default=Client.models.generate_order_number, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('day', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'فترة الصباح'), ('noon', 'فترة الظهر'), ('evening', 'فترة العصر'), ('engineer', 'حسب التنسيق مع المهندس')], max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'قيد الانتظار'), ('published', 'تم النشر'), ('in_progress', 'جاري الفحص'), ('completed', 'تم الانتهاء')], default='waiting', max_length=20, verbose_name='الحالة')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='الحي')),
                ('property_size', models.IntegerField(verbose_name='مساحة العقار (م2)')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='Admin.region', verbose_name='المدينة')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='Admin.inspectiontype', verbose_name='نوع الفحص')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitdetails', to='Client.order')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.propertypricing', verbose_name='نوع العقار')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع أرباح فحص'), ('withdraw', 'سحب رصيد لحساب بنكي')], default='deposit', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'معلق (تحت الإجراء)'), ('completed', 'مكتمل (نزل في الرصيد/تم السحب)'), ('failed', 'فاشلة'), ('refunded', 'مسترجعة للعميل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.order', verbose_name='الطلب المرتبط')),
            ],
        ),
    ]
