# Generated by Django 6.0.6 on 2026-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdetails',
            name='status',
            field=models.CharField(choices=[('waiting', 'قيد الانتظار'), ('published', 'تم النشر'), ('in_progress', 'جاري الفحص'), ('under_review', 'جاري المراجعة'), ('completed', 'تم الانتهاء')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='status',
            field=models.CharField(choices=[('waiting', 'قيد الانتظار'), ('published', 'تم النشر'), ('in_progress', 'جاري الفحص'), ('under_review', 'جاري المراجعة'), ('completed', 'تم الانتهاء')], default='waiting', max_length=20, verbose_name='الحالة'),
        ),
    ]
