# Generated by Django 6.0.6 on 2026-08-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_consultationdetails_status_and_more'),
        ('Engineer', '0002_engineer_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='engineer',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Engineer.wallet'),
            preserve_default=False,
        ),
    ]
