# Generated by Django 6.0.6 on 2026-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_remove_wallettransaction_engineer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق (تحت الإجراء)'), ('cancel', 'كنسل'), ('completed', 'مكتمل (نزل في الرصيد/تم السحب)'), ('failed', 'فاشلة'), ('refunded', 'مسترجعة للعميل')], default='pending', max_length=20),
        ),
    ]
