# Generated by Django 6.0.6 on 2026-08-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_remove_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.order', verbose_name='الطلب المرتبط'),
            preserve_default=False,
        ),
    ]
