# Generated by Django 6.0.6 on 2026-08-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_wallettransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.order', verbose_name='الطلب المرتبط'),
        ),
    ]
