# Generated by Django 6.0.6 on 2026-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_wallettransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
    ]
