# Generated by Django 6.0.6 on 2026-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_wallettransaction_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق (قيد العمل)'), ('completed', 'مكتمل (رصيد متاح)'), ('withdraw', 'تم السحب'), ('cancel', 'ملغي')], default='pending', max_length=20),
        ),
    ]
