# Generated by Django 6.0.6 on 2026-07-05 14:03

import Engineer.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ar', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='الاسم بالكامل (عربي)')),
                ('full_name_en', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\s]+$')], verbose_name='لاسم بالكامل (English)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='خطأ: يجب أن يحتوي الحقل على أرقام فقط، ويمكن أن يبدأ بعلامة + أو * في أول النص فقط.', regex='^[+]?[0-9]+$')], verbose_name='رقم الجوال الأساسي')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='خطأ: يجب أن يحتوي الحقل على أرقام فقط، ويمكن أن يبدأ بعلامة + أو * في أول النص فقط.', regex='^[+]?[0-9]+$')], verbose_name='رقم الجوال الثانوي')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='عدد سنوات الخبرة')),
                ('iban_number', models.CharField(max_length=35, verbose_name='رقم الآيبان (IBAN)')),
                ('iban_proof', models.FileField(upload_to=Engineer.models.DynamicPathUploader('ibans'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='إثبات الآيبان (PDF)')),
                ('iban_status', models.CharField(choices=[('required', 'مطلوب'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='required', max_length=20, verbose_name='الحالة رقم الآيبان (IBAN)')),
                ('iban_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات رقم الآيبان (IBAN)')),
                ('university_degree', models.FileField(upload_to=Engineer.models.DynamicPathUploader('degrees'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='الشهادة')),
                ('degree_status', models.CharField(choices=[('required', 'مطلوب'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='required', max_length=20, verbose_name='الحالة الشهادة')),
                ('degree_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات الشهادة')),
                ('sce_membership', models.FileField(upload_to=Engineer.models.DynamicPathUploader('sce'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='العضوية')),
                ('sce_status', models.CharField(choices=[('required', 'مطلوب'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='required', max_length=20, verbose_name='الحالة العضوية')),
                ('sce_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات العضوية')),
                ('cv_file', models.FileField(upload_to=Engineer.models.DynamicPathUploader('cvs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='السيرة الذاتية')),
                ('cv_status', models.CharField(choices=[('required', 'مطلوب'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='required', max_length=20, verbose_name='الحالة السيرة الذاتية')),
                ('cv_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات السيرة الذاتية')),
                ('equipment_photos', models.FileField(upload_to=Engineer.models.DynamicPathUploader('equipment'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='صور الأجهزة')),
                ('equipment_status', models.CharField(choices=[('required', 'مطلوب'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='required', max_length=20, verbose_name='الحالة صور الأجهزة')),
                ('equipment_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات صور الأجهزة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='Client.userphone', verbose_name='الحساب المرتبط')),
                ('city', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='Admin.region', verbose_name='المدينة')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=Engineer.models.DynamicPathUploader('avatar'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الرمزية')),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='عدد سنوات الخبرة')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_data', to='Engineer.engineerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Completed', 'مكتمل'), ('Rejected', 'مرفوض')], default='Pending', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='Engineer.wallet')),
            ],
        ),
    ]
