# Generated by Django 6.0.6 on 2026-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التفعيل'),
        ),
    ]
