# Generated by Django 6.0.6 on 2026-08-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0002_engineer_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='wallet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='Engineer.wallet'),
            preserve_default=False,
        ),
    ]
