# Generated by Django 6.0.6 on 2026-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0003_engineer_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
