# Generated by Django 6.0.6 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0004_remove_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
