# Generated by Django 6.0.6 on 2026-08-05 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0005_withdrawallog_delete_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawallog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
