# Generated by Django 6.0.6 on 2026-08-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0006_withdrawallog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawallog',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='Engineer.wallet'),
            preserve_default=False,
        ),
    ]
