# Generated by Django 6.0.6 on 2026-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0007_withdrawallog_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerapplication',
            name='status',
            field=models.CharField(choices=[('success', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='withdrawallog',
            name='status',
            field=models.CharField(choices=[('success', 'مقبول'), ('rejected', 'مرفوض')], default='success', max_length=10),
        ),
    ]
