# Generated by Django 6.0.6 on 2026-08-15 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0008_alter_engineerapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='engineerapplication',
            name='sce_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء عضوية الهيئة'),
        ),
        migrations.AddField(
            model_name='engineerapplication',
            name='sce_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عضوية هيئة المهندسين'),
        ),
        migrations.AddField(
            model_name='engineerapplication',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='عدد سنوات الخبرة'),
        ),
    ]
