# Generated by Django 6.0.6 on 2026-08-15 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0009_remove_engineer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerapplication',
            name='sce_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='رقم عضوية هيئة المهندسين'),
            preserve_default=False,
        ),
    ]
