# Generated by Django 6.0.6 on 2026-08-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0010_alter_engineerapplication_sce_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerapplication',
            name='experience_years',
        ),
    ]
