# Generated by Django 6.0.6 on 2026-08-15 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0011_remove_engineerapplication_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerapplication',
            name='years_of_experience',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='عدد سنوات الخبرة'),
        ),
    ]
