# Generated by Django 6.0.4 on 2026-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineer', '0012_alter_engineerapplication_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerapplication',
            name='status',
            field=models.CharField(choices=[('success', 'مقبول'), ('pending', 'قيد المراجعة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='withdrawallog',
            name='status',
            field=models.CharField(choices=[('success', 'مقبول'), ('pending', 'قيد المراجعة'), ('rejected', 'مرفوض')], default='success', max_length=10),
        ),
    ]
